### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by sagangwee** [sagangwee/safespace#1]
#### Quiz / Tutorial
- [ ] Link to intro video after sign up 
- [ ] Link to 5 question quiz after watching video 
- [ ] Link to liability page after successfully completing video quiz 
- [ ] Link to People page after signing liability  
#### Filter Search
- [x] Clicking the online link doesn't update the results 
- [x] Dynamically display flash messages when adding friends 
- [x] Replace the add friend link with a plus icon and update tutorial tooltip positioning accordingly  
#### Chat
- [x] Download chat 
- [x] Delete chat weekly 
- [ ] Recommend Button 
- [x] Add a sidebar on the right of the chat box with the profile info of the user you are talking to 
- [ ] Figure something out for the "previous" link  
- [ ] Mute button 
- [x] Block user button 
- [ ] Chat notifications  
### Styling
- [x] Style the scroll bar of the chat 
- [ ] Fill and style the Contact page 
- [ ] Organize the ugly profile pages 
- [ ] Restyle nav bar 
- [ ] Add a Favicon
