### ISSUE TITLE
Task List

### ISSUE THREAD

**Issue by sagangwee** [sagangwee/safespace#16]
#### Quiz / Tutorial
- [x] Link to intro video after sign up 
- [x] Link to 5 question quiz after watching video 
- [x] Link to liability page after successfully completing video quiz 
- [x] Link to creating profile characteristics after signing liability w/ prefer not to answer (Fill out your anonymous bio!)
- [x] Link to People page after creating profile 
- [x] Directions in tutorial
#### Filter Search
- [x] Clicking the online link doesn't update the results 
- [x] Dynamically display flash messages when adding friends 
- [x] Replace the add friend link with a plus icon and update tutorial tooltip positioning accordingly  
- [x] Rank preferences (next to characteristic w/ tooltip)
#### Chat
- [x] Download chat 
- [x] Delete chat weekly 
- [x] Recommend Button 
- [x] Add a sidebar on the right of the chat box with the profile info of the user you are talking to 
- [ ] Figure something out for the "previous" link  
- [x] Mute button 
- [x] Block user button 
- [x] Chat notifications  
#### Peer Counselors
- [x] Add Peer Counselor as a friend on user sign up
- [x] Create separate sign up process for peer counselors with universal pass code
- [x] Create recommendation form
- [x] Create a view for recommendation requests
- [x] Add ability to unlock/open/accept recommendation request
#### About Page
- [ ] Add more content from SafeSpace proposal
- [ ] Add YikYak comments with CSS speech bubbles
- [ ] Add Donors
### Styling
- [x] Style the scroll bar of the chat 
- [x] Fill and style the Contact page 
- [ ] Organize the ugly profile pages (perhaps model after Facebook-style inline editing with grid sections)
- [ ] Restyle nav bar 
- [ ] Add a Favicon
- [ ] Add a footer
- [ ] Decide on a consistent color scheme
